import {escape as e, icon, hydrateIcons, formatNumber, label, valueText, tableHTML, contractHTML, chartHTML} from './ui.js';

const SOURCE='https://github.com/liu-XI71/liu-xi-ai-analyst';
const OLD='https://liu-xi71.github.io/';
const TASKS={growth:[['diagnose','异常诊断'],['experiment','实验复盘'],['report','增长周报']],repurchase:[['segment','分群与留出方案'],['diagnose','复购诊断'],['report','运营报告']]};
const FALLBACK={domains:[{id:'growth',name:'增长诊断与自动周报',description:'确认留存口径，查询成熟队列，分解结构和表现，复盘随机实验并交付证据。',data_source:'固定种子生成的合成用户与活动数据',data_range:{start:'2026-08-01',end:'2026-09-07'},default_request:{task:'diagnose',start:'2026-08-24',end:'2026-08-30',compare_start:'2026-08-17',compare_end:'2026-08-23',filters:{}},examples:[{question:'比较最近两周已完成观察的新增队列，次 7 日内留存为什么变化？按渠道和设备检查。',task:'diagnose'},{question:'复盘 8 月 17—30 日的随机增长实验，检查提升、置信区间、SRM 和成本门槛。',task:'experiment'},{question:'生成增长周报，展示变化、分层证据、假设和下一步建议。',task:'report'}]},{id:'repurchase',name:'复购运营 Agent',description:'从正向订单计算成熟队列复购、时点 RFM 分群、预算内匿名候选和可复现随机留出建议。',data_source:'固定种子生成的匿名合成订单',data_range:{start:'2026-01-01',end:'2026-06-30'},default_request:{question:'截至5月31日，按历史购买分群，在200元预算内制定召回候选与随机留出方案。',task:'segment',start:'2026-03-01',end:'2026-05-31',filters:{budget:200,contact_cost:2,holdout_ratio:.2}},examples:[{question:'截至5月31日，按历史购买分群，在200元预算内制定召回候选与随机留出方案。',task:'segment'},{question:'分析3月至5月首次观察购买队列的次7日和次30日复购，按地区拆分。',task:'diagnose'},{question:'生成复购运营报告，说明成熟窗口、候选预算和留出计划。',task:'report'}]}],model:{configured:false,mode:'demo',model:null},version:'1.0'};
const state={accessToken:'',catalog:FALLBACK,online:false,ready:false,page:'overview',apiBase:readStorage('lx-analyst-api')||'',requestVersion:0,controller:null,result:null,mode:'demo',snapshots:{},evaluation:null};
const main=document.querySelector('#main');
function readStorage(k){try{return localStorage.getItem(k);}catch{return null;}}
function saveStorage(k,v){try{v?localStorage.setItem(k,v):localStorage.removeItem(k);}catch{}}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),3200);}
function domainMeta(id=state.page){return state.catalog.domains?.find(d=>d.id===id)||FALLBACK.domains.find(d=>d.id===id);}
function url(path){return `${state.apiBase.replace(/\/$/,'')}${path}`;}
async function fetchJSON(path,{timeout=12000,...options}={}){
  const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);
  const externalSignal=options.signal;if(externalSignal){if(externalSignal.aborted)c.abort();else externalSignal.addEventListener('abort',()=>c.abort(),{once:true});}
  try{const r=await fetch(path,{...options,signal:c.signal,headers:{'Content-Type':'application/json',...(typeof path==='string'&&path.startsWith(url('/api/'))&&state.accessToken?{Authorization:`Bearer ${state.accessToken}`} : {}),...(options.headers||{})}});if(!r.ok){let msg;try{const data=await r.json();msg=typeof data.detail==='string'?data.detail:Array.isArray(data.detail)?data.detail.map(x=>`${x.loc?.slice(-1).join('')||'参数'}：${x.msg}`).join('；'):data.message;}catch{}throw new Error(msg||`请求失败（HTTP ${r.status}）`);}return await r.json();}finally{clearTimeout(timer);}
}
async function readSnapshot(id){if(state.snapshots[id])return state.snapshots[id];const data=await fetchJSON(new URL(`./demo/${id}.json`,import.meta.url),{timeout:7000});state.snapshots[id]=data;return data;}
function setConnection(){const el=document.querySelector('#connection-status');el.className=`connection-status ${state.online?'online':'offline'}`;el.innerHTML=`<i></i>${!state.ready?'正在连接':state.online?'分析 API 已连接':'静态回放模式'}`;el.title=state.online?'可以提交新问题，调用后端计算':'当前未连接后端；仅展示已保存的分析快照';}
async function connect(){
  state.ready=false;setConnection();
  try{const catalog=await fetchJSON(url('/api/v1/catalog'),{timeout:6500});if(!Array.isArray(catalog.domains))throw new Error('后端返回的目录格式不正确');state.catalog=catalog;state.online=true;}
  catch{state.online=false;try{const catalog=await readSnapshot('catalog');if(Array.isArray(catalog.domains))state.catalog=catalog;}catch{state.catalog=FALLBACK;}}
  state.ready=true;setConnection();render();
}
function sectionHeading(number,english,title,description='',link=''){return `<div class="section-heading"><div><span class="eyebrow">${e(english)}</span><h2><span class="section-number">${number}</span>${e(title)}</h2>${description?`<p>${e(description)}</p>`:''}</div>${link}</div>`;}
function render(){
  const raw=location.hash.slice(1).split('?')[0];state.page=['overview','growth','repurchase','evaluation','about'].includes(raw)?raw:'overview';
  document.querySelectorAll('.nav-link').forEach(a=>{const active=a.dataset.page===state.page;a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');});
  document.querySelector('#breadcrumb-current').textContent={overview:'作品总览',growth:'增长诊断',repurchase:'复购运营',evaluation:'评测与可靠性',about:'项目资料'}[state.page];
  document.title=`${{overview:'刘希 · AI 数据分析作品集',growth:'增长诊断 · 刘希',repurchase:'复购运营 · 刘希',evaluation:'评测与可靠性 · 刘希',about:'项目资料 · 刘希'}[state.page]}`;
  document.querySelector('#sidebar').classList.remove('open');document.querySelector('#mobile-toggle').setAttribute('aria-expanded','false');updateSidebarAccessibility();
  state.controller?.abort();state.requestVersion++;state.result=null;
  if(state.page==='overview')renderOverview();else if(state.page==='growth'||state.page==='repurchase')renderWorkbench();else if(state.page==='evaluation')renderEvaluation();else renderAbout();
}

function renderOverview(){
  main.innerHTML=`
  <section class="hero" aria-labelledby="hero-title"><div class="hero-copy">
    <div class="hero-intro"><i></i>刘希 · 业务型 AI 数据分析师</div>
    <h1 id="hero-title">把问题问清，<br>让数据<em>给出答案。</em></h1>
    <p class="hero-description">把业务问题转成可核验的数据结论，<br>把重复分析做成可复用的 AI 工作流。</p>
    <div class="hero-actions"><a class="button button-primary" href="#growth">体验增长分析 ${icon('arrow-right')}</a><a class="button button-secondary" href="#about">了解项目方法 ${icon('book')}</a></div>
    <div class="hero-caption"><span>${icon('database')}合成数据，真实计算</span><span>${icon('check')}每条结论可追溯</span></div>
  </div><div class="signal-card" aria-label="增长分析工作流预览"><div class="signal-header"><span>GROWTH INTELLIGENCE</span><span class="signal-status"><i></i>可核验的分析流程</span></div><div class="signal-label">从一个业务问题开始</div><p class="signal-question">留存为什么变化？<br><span>先看口径，再看证据。</span></p><div class="pipeline"><span>业务 Skill</span><b>→</b><span>Python + SQL</span><b>→</b><span>验证与报告</span></div><div class="signal-chart" id="hero-chart"><div class="signal-chart-header"><span>每个答案，都有一条证据链</span><span>01 — 04</span></div><div class="preview-flow"><div style="font:10px/2 var(--mono);color:#7bb9aa">metric → readonly query → result → report</div><div style="font-size:11px;color:#96b9ba;line-height:2.1">指标口径与数据窗口 · 实际执行的 SQL<br>分层变化与统计检查 · 可下载分析报告</div></div></div><div class="signal-bottom"><span>PERSONAL PROJECT / SYNTHETIC DATA</span><span class="mini-stat">业务 × 工程</span></div></div></section>
  <div class="method-strip"><div class="method-item"><div class="method-icon">${icon('book')}</div><div><strong>业务知识工程</strong><small>口径、边界与分析 SOP</small></div></div><div class="method-item"><div class="method-icon">${icon('terminal')}</div><div><strong>Python 工具调用</strong><small>取数、计算与结果验证</small></div></div><div class="method-item"><div class="method-icon">${icon('chart')}</div><div><strong>分析交付自动化</strong><small>图表、结论与报告</small></div></div><div class="method-item"><div class="method-icon">${icon('check')}</div><div><strong>用评测说明能力</strong><small>正确性与失败边界</small></div></div></div>
  ${sectionHeading('01','FEATURED PROJECT','增长诊断与自动周报','从自然语言问题，到一份有证据的分析交付。',`<a class="text-link" href="#evaluation">查看评测 ${icon('arrow-right')}</a>`)}
  <article class="featured-project"><div><div class="project-label"><span>FLAGSHIP / 01</span><span class="tag tag-green">个人 AI 项目</span></div><h3>让增长分析，<br>从每周重复变成随时可用。</h3><p class="project-copy">围绕留存变化、渠道结构和随机实验，串起业务口径、数据库查询、确定性计算与报告。支持逐步查看工具执行记录和原始证据。</p><div class="tech-tags"><span>PYTHON / FASTAPI</span><span>SQLITE</span><span>OPENAI TOOL CALLING</span><span>BUSINESS SKILL</span></div><div class="project-actions"><a class="button button-primary" href="#growth">进入增长工作台 ${icon('arrow-right')}</a><a class="text-link" href="${SOURCE}" target="_blank" rel="noopener">查看源码 ${icon('arrow-up')}</a></div></div><div class="project-preview"><div class="preview-heading"><span>一次分析的交付路径</span>${icon('layers')}</div><div class="preview-flow"><div class="preview-step"><span class="step-num">01</span><strong>确认指标、窗口与分析范围</strong><small>业务口径</small></div><div class="preview-step"><span class="step-num">02</span><strong>查询成熟队列，拆解变化</strong><small>SQL + Python</small></div><div class="preview-step"><span class="step-num">03</span><strong>区分事实、假设与行动</strong><small>证据校验</small></div><div class="preview-step final"><span class="step-num">04</span><strong>生成图表和可下载报告</strong><small>分析交付</small></div></div><p class="preview-note">确定性演示与真实模型调用分开标识。<br>实时模式取决于后端模型配置，静态站点提供保存的运行回放。</p></div></article>
  ${sectionHeading('02','BUSINESS FOUNDATION','增长与实验业务案例','保留业务判断、指标方法和策略验证的基础。')}
  <article class="business-card"><div><span class="eyebrow">BUSINESS CASE / ORIGINAL PORTFOLIO</span><h3>先理解业务，<br>再决定怎样分析。</h3></div><p>原版作品集保留增长与留存分析、实验评估及个人参与说明。新 AI 项目沿用分析方法，使用独立合成数据演示，个人项目能力与实习经历分别表述。</p><a class="button button-secondary" href="${OLD}" target="_blank" rel="noopener">查看原版业务案例 ${icon('arrow-up')}</a></article>
  ${sectionHeading('03','REUSABLE TOOLS','让分析方法走进更多场景','从文件诊断，到复购运营的决策支持。')}
  <div class="project-grid"><article class="project-card"><div class="project-card-top"><span class="project-card-icon">${icon('file')}</span><span class="tag">原有作品</span></div><h3>CSV 分析工作台</h3><p>确认字段与指标口径，检查数据质量，完成分群诊断与报告导出。把一次分析中的方法沉淀为可重复运行的工具。</p><div class="tech-tags"><span>DATA QUALITY</span><span>SEGMENT ANALYSIS</span><span>REPORT</span></div><div class="project-card-bottom"><span>文件 → 口径 → 诊断 → 报告</span><a class="text-link" href="https://github.com/liu-XI71/liu-xi-csv-analyst" target="_blank" rel="noopener">查看原项目 ${icon('arrow-up')}</a></div></article><article class="project-card"><div class="project-card-top"><span class="project-card-icon">${icon('users')}</span><span class="tag tag-green">新增 AI 场景</span></div><h3>复购运营 Agent</h3><p>基于成熟观察窗口分析复购，用时点 RFM 分群、预算约束和随机留出建议，形成可以核对的运营候选方案。</p><div class="tech-tags"><span>RFM</span><span>BUDGET CONSTRAINT</span><span>HOLDOUT</span></div><div class="project-card-bottom"><span>合成订单 · 无实际触达</span><a class="text-link" href="#repurchase">进入运营工作台 ${icon('arrow-right')}</a></div></article></div>
  <div class="boundary-note">${icon('info')}<p>演示数据由固定种子合成，不代表企业真实经营结果。页面展示的能力、评测与运行模式均以当前项目实际实现为准。</p></div>`;
  readSnapshot('growth').then(data=>{if(state.page!=='overview')return;const chart=data.charts?.[0];if(chart)document.querySelector('#hero-chart').innerHTML=`<div class="signal-chart-header"><span>${e(chart.title)}</span><span>合成数据 · 保存快照</span></div>${chartHTML(chart,{dark:true,compact:true})}`;}).catch(()=>{});
}

function renderWorkbench(){
  const domain=state.page,meta=domainMeta(),def=meta.default_request||{},growth=domain==='growth';state.mode='demo';
  main.innerHTML=`<div class="page-heading"><div><span class="eyebrow">${growth?'GROWTH INTELLIGENCE':'RETENTION OPERATIONS'}</span><h1>${growth?'增长诊断工作台':'复购运营工作台'}</h1><p>${e(meta.description)}</p></div><div class="page-heading-right"><span class="tag tag-green">个人项目</span><span class="tag">合成数据</span></div></div>
  <div class="workspace-layout"><section class="query-panel" aria-labelledby="query-panel-title"><div class="query-panel-head"><h2 id="query-panel-title">发起一次分析</h2><span>01 / INPUT</span></div><form id="query-form" class="query-form">
  <div class="form-field question-field"><div class="field-label-row"><label for="question" class="field-label">你的业务问题</label><span>${state.online?'支持中文提问':'保存的示例问题'}</span></div><textarea id="question" class="question-input" maxlength="3000" ${state.online?'':'readonly'}>${e(def.question||meta.examples?.[0]?.question||'')}</textarea><div class="example-list">${(meta.examples||[]).map((x,i)=>`<button type="button" class="example-button" data-example="${i}" ${state.online?'':'disabled'}>${e(TASKS[domain].find(t=>t[0]===x.task)?.[1]||`示例 ${i+1}`)}</button>`).join('')}</div>${!state.online?'<p class="form-snapshot">静态回放展示固定问题的已保存结果。连接 API 后可编辑问题与参数。</p>':''}</div>
  <div class="form-field task-field"><label class="field-label" for="task">分析任务</label><select id="task" ${state.online?'':'disabled'}>${TASKS[domain].map(([id,name])=>`<option value="${id}" ${id===def.task?'selected':''}>${name}</option>`).join('')}</select></div>
  <div class="form-field mode-field"><label class="field-label" id="mode-label">执行模式</label><div class="mode-select" role="group" aria-labelledby="mode-label"><button type="button" class="mode-option active" data-mode="demo" aria-pressed="true">${state.online?'确定性演示':'离线快照'}</button><button type="button" class="mode-option" data-mode="live" aria-pressed="false" ${state.online&&state.catalog.model?.configured?'':'disabled'}>真实 OpenAI</button></div><p class="field-help" id="mode-help">${state.online?'演示模式使用有限意图路由和参数化查询，不调用大模型。':'离线回放不执行新查询，不调用大模型。'}${state.online&&!state.catalog.model?.configured?' 后端暂未配置模型。':''}</p></div>
  <details class="form-details" open><summary>时间窗口与筛选 ${icon('chevron')}</summary><div class="date-grid"><div><label for="start">分析开始</label><input id="start" type="date" class="text-input" value="${e(def.start||'')}" ${state.online?'':'disabled'}></div><div><label for="end">分析结束</label><input id="end" type="date" class="text-input" value="${e(def.end||'')}" ${state.online?'':'disabled'}></div>${growth?`<div class="compare-field"><label for="compare-start">对比开始</label><input id="compare-start" type="date" class="text-input" value="${e(def.compare_start||'')}" ${state.online?'':'disabled'}></div><div class="compare-field"><label for="compare-end">对比结束</label><input id="compare-end" type="date" class="text-input" value="${e(def.compare_end||'')}" ${state.online?'':'disabled'}></div>`:''}</div><div class="date-grid" id="domain-filters">${renderFilterFields(meta,growth)}</div><p class="field-help">${e(meta.data_source||'合成演示数据')}<br>数据范围：${e(meta.data_range?.start||'—')} — ${e(meta.data_range?.end||'—')}</p></details>
  <button class="button button-primary button-block query-submit" id="run-analysis" type="submit" ${state.ready?'':'disabled'}>${icon(state.online?'spark':'play')}<span>${state.online?'开始分析':'查看保存的分析回放'}</span>${icon('arrow-right')}</button>
  </form><div class="query-panel-foot">${icon('lock')}只读取数 · 确定性计算 · 不执行业务触达</div></section>
  <section class="workspace-results" aria-label="分析结果" aria-live="polite" aria-busy="false"><div id="result-notice">${state.online?'':`<div class="notice notice-amber workspace-notice">${icon('info')}<p>当前为静态作品展示。回放来自已保存的实际计算；新问题和真实模型调用需要连接后端。<button class="text-link" id="connect-inline" style="border:0;background:none;font-size:inherit;padding:0 0 0 5px">配置 API ↗</button></p></div>`}</div><div id="analysis-result">${emptyHTML(growth)}</div></section></div>`;
  document.querySelector('#query-form').addEventListener('submit',submitAnalysis);
  document.querySelectorAll('[data-example]').forEach(btn=>btn.addEventListener('click',()=>{const ex=meta.examples[Number(btn.dataset.example)];document.querySelector('#question').value=ex.question;document.querySelector('#task').value=ex.task;updateTaskFields(ex.task,true);invalidateResult();}));
  document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});document.querySelector('#mode-help').textContent=state.mode==='live'?`真实调用 ${state.catalog.model?.model||'OpenAI'} 进行任务规划与工具调用；数值由数据库及 Python 计算。`:'演示模式使用有限意图路由和参数化查询，不调用大模型。';invalidateResult();}));
  document.querySelector('#task').addEventListener('change',ev=>{updateTaskFields(ev.target.value,true);invalidateResult();});
  document.querySelector('#query-form').addEventListener('input',()=>invalidateResult());
  document.querySelector('#query-form').addEventListener('change',ev=>{if(ev.target.id!=='task')invalidateResult();});
  document.querySelector('#connect-inline')?.addEventListener('click',openSettings);
  updateTaskFields(def.task||TASKS[domain][0][0],false);
  if(!state.online)readSnapshot(domain).then(snapshot=>{if(state.page!==domain||state.online)return;const request={...def,...(snapshot.request||{})};if(request.question)document.querySelector('#question').value=request.question;if(request.task)document.querySelector('#task').value=request.task;for(const [key,id] of [['start','start'],['end','end'],['compare_start','compare-start'],['compare_end','compare-end']]){const input=document.getElementById(id);if(input&&request[key])input.value=request[key];}updateTaskFields(request.task,false);}).catch(()=>{});
}
function renderFilterFields(meta,growth){
  const disabled=state.online?'':'disabled',filters=meta.filters||{};
  if(growth)return ['channel','device'].map(key=>`<div><label for="filter-${key}">${key==='channel'?'获客渠道':'设备'}</label><select id="filter-${key}" ${disabled}><option value="">全部${key==='channel'?'渠道':'设备'}</option>${(Array.isArray(filters[key])?filters[key]:[]).map(item=>`<option value="${e(typeof item==='object'?item.value:item)}">${e(typeof item==='object'?item.label:item)}</option>`).join('')}</select></div>`).join('');
  return `<div><label for="filter-region">地区</label><select id="filter-region" ${disabled}><option value="">全部地区</option>${(Array.isArray(filters.region)?filters.region:[]).filter(v=>v!=='all').map(v=>`<option value="${e(v)}">${e(v)}</option>`).join('')}</select></div><div><label for="filter-budget">计划预算（元）</label><input id="filter-budget" class="text-input" type="number" min="0" max="1000000" step="1" value="${e(meta.default_request?.filters?.budget??200)}" ${disabled}></div>`;
}
function updateTaskFields(task,reset){if(state.page!=='growth')return;const experiment=task==='experiment';document.querySelectorAll('.compare-field').forEach(el=>el.hidden=experiment);if(reset){const d=domainMeta().default_request||{};document.querySelector('#start').value=experiment?'2026-08-17':d.start||'';document.querySelector('#end').value=experiment?'2026-08-30':d.end||'';document.querySelector('#compare-start').value=experiment?'':d.compare_start||'';document.querySelector('#compare-end').value=experiment?'':d.compare_end||'';}}
function emptyHTML(growth){return `<div class="empty-panel"><div class="empty-icon">${icon(growth?'trend':'users')}</div><h2>${growth?'从业务问题，走到证据':'从客户行为，走到运营方案'}</h2><p>${growth?'选择一个任务，提出你的问题。分析将确认口径、读取数据，给出图表与可核验的结论。':'选择分析范围，查看成熟复购表现、历史分群与预算内的随机留出方案。'}</p><div class="empty-flow"><div class="empty-flow-item"><span>1</span>确认口径</div><div class="empty-flow-item"><span>2</span>取数分析</div><div class="empty-flow-item"><span>3</span>交付证据</div></div><div class="empty-hint">${state.online?'结果将展示实际 SQL、工具记录、数据来源和可下载报告。':'点击左侧按钮，查看这一业务问题的完整分析回放。'}</div></div>`;}
function invalidateResult(){state.requestVersion++;state.controller?.abort();state.controller=null;if(state.result||document.querySelector('.loading-panel')){state.result=null;const el=document.querySelector('#analysis-result');if(el)el.innerHTML=emptyHTML(state.page==='growth');}setBusy(false);}
function setBusy(busy){const button=document.querySelector('#run-analysis');if(!button)return;button.disabled=busy||!state.ready;button.innerHTML=busy?'<span class="spinner"></span><span>分析进行中…</span>':`${icon(state.online?'spark':'play')}<span>${state.online?'开始分析':'查看保存的分析回放'}</span>${icon('arrow-right')}`;document.querySelector('.workspace-results')?.setAttribute('aria-busy',String(busy));}
async function submitAnalysis(event){
  event.preventDefault();const domain=state.page,meta=domainMeta(),question=document.querySelector('#question').value.trim();if(!question){toast('请先输入一个业务问题。');document.querySelector('#question').focus();return;}
  state.controller?.abort();const version=++state.requestVersion;state.controller=new AbortController();state.result=null;setBusy(true);
  const area=document.querySelector('#analysis-result');area.innerHTML=`<div class="loading-panel"><span class="spinner"></span><h2>${state.online?'正在分析你的问题':'正在读取分析回放'}</h2><p>${state.online?'实际执行步骤将在完成后展示，请稍候。':'读取保存的结果、证据和工具记录。'}</p><div class="loading-steps"><div class="loading-step"><span></span>${state.online?'等待后端任务执行':'加载已保存的结果'}</div><div class="loading-step"><span></span>每个数值保留来源与指标口径</div></div></div>`;
  try{
    let data;
    if(!state.online){data=await readSnapshot(domain);data={...data,_replay:true};}
    else{
      const task=document.querySelector('#task').value;const body={question,domain,task,mode:state.mode,filters:{...(meta.default_request?.filters||{})}};
      for(const [key,id] of [['start','start'],['end','end'],['compare_start','compare-start'],['compare_end','compare-end']]){if(task==='experiment'&&key.startsWith('compare_'))continue;const v=document.getElementById(id)?.value;if(v)body[key]=v;}
      if(domain==='growth'){for(const key of ['channel','device']){const v=document.querySelector(`#filter-${key}`)?.value;if(v)body.filters[key]=v;else delete body.filters[key];}}
      else {const region=document.querySelector('#filter-region')?.value;if(region)body.filters.region=region;else delete body.filters.region;body.filters.budget=Number(document.querySelector('#filter-budget').value);}
      if(body.start&&body.end&&body.start>body.end)throw new Error('分析开始日期不能晚于结束日期。');
      if(body.compare_start&&body.compare_end&&body.compare_start>body.compare_end)throw new Error('对比开始日期不能晚于结束日期。');
      data=await fetchJSON(url('/api/v1/analyze'),{method:'POST',body:JSON.stringify(body),signal:state.controller.signal,timeout:125000});
    }
    if(version!==state.requestVersion)return;state.result=data;renderResult(data);
  }catch(err){if(version!==state.requestVersion)return;const message=err.name==='AbortError'?'请求超时或已取消。请稍后重新运行；未生成的结果不会显示为成功。':err.message;area.innerHTML=`<div class="error-panel"><div class="error-icon">${icon('alert')}</div><h2>${state.online?'这次分析未能完成':'暂时无法读取回放'}</h2><p>${e(message)}</p><button class="button button-secondary" id="retry-analysis">${icon('refresh')}重新尝试</button></div>`;document.querySelector('#retry-analysis')?.addEventListener('click',()=>document.querySelector('#query-form').requestSubmit());}
  finally{if(version===state.requestVersion)setBusy(false);}
}

function renderResult(data){
  const area=document.querySelector('#analysis-result');const replay=data._replay,completed=data.status==='completed';
  const mode=replay?'保存的计算快照':data.mode==='live'?'真实模型 + 工具调用':'确定性演示 · 未调用模型';
  const date=data.created_at?new Date(data.created_at).toLocaleString('zh-CN',{hour12:false}):'时间未记录';
  area.innerHTML=`${replay?`<div class="notice notice-info replay-banner">${icon('clock')}<p>回放来源：已保存的合成数据运行。本次只读取快照，不执行 SQL 或模型调用。${data.request?.question?`<br>原问题：${e(data.request.question)}`:''}</p></div>`:''}<div class="result-titlebar"><div><h2>${e(data.title||'分析结果')}</h2><div class="result-meta"><span class="tag ${completed?'tag-green':'tag-amber'}">${completed?'分析完成':data.status==='needs_clarification'?'需要补充信息':'数据不足'}</span><span>${e(mode)}</span><span>${e(date)}</span>${data.run_id?`<code title="${e(data.run_id)}">#${e(data.run_id.slice(0,8))}</code>`:''}</div></div><div class="result-actions"><button class="button button-secondary" data-download="html">${icon('download')}HTML 报告</button><button class="button button-secondary" data-download="md">${icon('file')}Markdown</button></div></div>
  ${data.summary?`<div class="result-summary">${e(data.summary)}</div>`:''}
  ${data.clarification?`<div class="suggestion-box"><h3>先把问题确认清楚</h3><p>${e(data.clarification.question)}</p><div class="suggestion-options">${(data.clarification.options||[]).map((opt,i)=>`<button class="button button-secondary" data-clarify="${i}">${e(opt)}</button>`).join('')}</div></div>`:''}
  ${Array.isArray(data.kpis)&&data.kpis.length?`<div class="kpi-grid">${data.kpis.map(k=>renderKPI(k)).join('')}</div>`:''}
  ${(data.charts||[]).map(chart=>`<section class="result-section"><div class="result-section-head"><h3>${e(chart.title)}</h3><span>${e(chart.type||'CHART').toUpperCase()}</span></div><div class="chart-wrap">${chartHTML(chart)}</div></section>`).join('')}
  ${data.findings?.length?`<section class="result-section"><div class="result-section-head"><h3>分析结论与下一步</h3><span>FINDINGS</span></div><div class="result-section-body"><div class="finding-list">${data.findings.map(f=>`<div class="finding-item"><span class="finding-kind ${e(f.kind)}">${{fact:'事实',hypothesis:'假设',action:'行动'}[f.kind]||'说明'}</span><div>${e(f.text)}${f.evidence_ids?.length?`<div>${f.evidence_ids.map(id=>`<a class="evidence-reference" href="#${e(id)}" data-evidence="${e(id)}">↳ ${e(id)}</a>`).join('')}</div>`:''}</div></div>`).join('')}</div></div></section>`:''}
  <section class="result-section"><div class="result-tabs" role="tablist" aria-label="结果详情"><button class="result-tab active" role="tab" aria-selected="true" aria-controls="pane-data" id="tab-data" data-tab="data">结果数据</button><button class="result-tab" role="tab" aria-selected="false" aria-controls="pane-evidence" id="tab-evidence" data-tab="evidence" tabindex="-1">SQL 证据 <span>${(data.evidence||[]).length}</span></button><button class="result-tab" role="tab" aria-selected="false" aria-controls="pane-trace" id="tab-trace" data-tab="trace" tabindex="-1">执行记录</button><button class="result-tab" role="tab" aria-selected="false" aria-controls="pane-contract" id="tab-contract" data-tab="contract" tabindex="-1">指标口径</button></div><div class="tab-pane" id="pane-data" role="tabpanel" aria-labelledby="tab-data">${data.tables?.length?data.tables.map(t=>`<div class="table-block"><div class="table-caption">${e(t.title)}<small>${t.rows?.length||0} 行</small></div>${tableHTML(t)}</div>`).join(''):'<p class="field-help">当前结果没有数据表；请查看分析说明。</p>'}</div><div class="tab-pane" id="pane-evidence" role="tabpanel" aria-labelledby="tab-evidence" hidden>${renderEvidence(data.evidence||[])}</div><div class="tab-pane" id="pane-trace" role="tabpanel" aria-labelledby="tab-trace" hidden>${renderTrace(data.trace||[])}</div><div class="tab-pane" id="pane-contract" role="tabpanel" aria-labelledby="tab-contract" hidden>${contractHTML(data.metric_contract||{})}</div></section>
  ${data.suggestions?.length?`<div class="suggestion-box"><h3>可以继续检查</h3><p>${data.suggestions.map(s=>e(s)).join('<br>')}</p></div>`:''}
  ${data.limitations?.length?`<details class="result-limitations" open><summary>数据与结论的使用边界</summary><ul>${data.limitations.map(l=>`<li>${e(l)}</li>`).join('')}</ul></details>`:''}`;
  document.querySelectorAll('[data-download]').forEach(btn=>btn.addEventListener('click',()=>downloadReport(btn.dataset.download,data,btn)));
  document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>selectResultTab(btn.dataset.tab)));
  document.querySelector('.result-tabs').addEventListener('keydown',event=>{const tabs=[...document.querySelectorAll('[data-tab]')],index=tabs.indexOf(document.activeElement);if(index<0)return;let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();selectResultTab(tabs[next].dataset.tab);tabs[next].focus();});
  document.querySelectorAll('[data-evidence]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();selectResultTab('evidence');const detail=document.getElementById(`evidence-${link.dataset.evidence}`);if(detail){detail.open=true;detail.scrollIntoView({behavior:'smooth',block:'start'});}}));
  document.querySelectorAll('[data-clarify]').forEach(btn=>btn.addEventListener('click',()=>{if(!state.online){toast('连接 API 后可重新提交问题。');return;}const opt=data.clarification.options[Number(btn.dataset.clarify)];document.querySelector('#question').value=`${document.querySelector('#question').value}\n补充信息：${opt}`;invalidateResult();document.querySelector('#question').focus();}));
}
function renderKPI(k){const ratio=['ratio','proportion'].includes(k.unit),value=typeof k.value==='number'&&ratio?k.value*100:k.value;const unit={ratio:'%',proportion:'%',count:'人',customers:'人',CNY:'元'}[k.unit]||k.unit||'';return `<div class="kpi-card"><div class="kpi-label">${e(k.label||k.id)}</div><div class="kpi-value">${e(formatNumber(value))}<span>${e(unit)}</span></div>${k.previous!==undefined?`<div class="kpi-change">对比期 <b>${e(formatNumber(ratio&&k.previous!==null?k.previous*100:k.previous))}${e(unit)}</b>${k.delta!==undefined?` · 变化 ${Number(k.delta)>0?'+':''}${e(formatNumber(k.delta))}${e(k.delta_unit||(unit==='%'?'个百分点':unit))}`:''}</div>`:`<div class="kpi-change">${e(k.note||'来自本次查询结果')}</div>`}</div>`;}
function renderEvidence(evidence){return evidence.length?evidence.map(item=>`<details class="evidence-card" id="evidence-${e(item.id)}"><summary><span>${e(item.label||item.id)} <code>${e(item.id)}</code></span>${icon('chevron')}</summary><pre><code>${e(item.sql||'此证据由确定性工具计算，无 SQL。')}</code></pre><div class="evidence-info">参数：<span class="raw-value">${e(JSON.stringify(item.parameters??{}))}</span><br>来源：${e(item.source||'未记录')}<br>口径版本：${e(item.metric_version||'未记录')}</div>${tableHTML({rows:item.rows||[]},40)}</details>`).join(''):'<p class="field-help">本次任务尚未执行数据查询。</p>';}
function renderTrace(trace){return trace.length?`<div class="trace-list">${trace.map(t=>`<div class="trace-item"><span class="trace-dot">${icon(['failed','error'].includes(t.status)?'alert':'tick')}</span><div><div class="trace-title"><code>${e(t.tool||'tool')}</code><span class="tag ${['failed','error'].includes(t.status)?'tag-amber':'tag-green'}">${e({completed:'完成',success:'完成',skipped:'跳过',failed:'失败',error:'失败',blocked:'已拦截'}[t.status]||t.status||'已记录')}</span></div><p class="trace-description">${e(t.description||'')}</p></div><span class="trace-time">${t.duration_ms!==undefined?`${e(formatNumber(t.duration_ms,1))} ms`:''}</span></div>`).join('')}</div>`:'<p class="field-help">没有可展示的执行记录。</p>';}
function selectResultTab(name){document.querySelectorAll('[data-tab]').forEach(btn=>{const active=btn.dataset.tab===name;btn.classList.toggle('active',active);btn.setAttribute('aria-selected',String(active));btn.tabIndex=active?0:-1;});document.querySelectorAll('.tab-pane').forEach(p=>p.hidden=p.id!==`pane-${name}`);}

function reportMD(data){
  const rowsToMD=(rows,columns)=>{if(!rows?.length)return '_无数据_';const cols=columns?.length?columns:Object.keys(rows[0]);const cell=v=>valueText(v).replaceAll('|','\\|').replaceAll('\n',' ');return `| ${cols.map(label).join(' | ')} |\n| ${cols.map(()=> '---').join(' | ')} |\n${rows.map(r=>`| ${cols.map(c=>cell(r[c])).join(' | ')} |`).join('\n')}`;};
  return `# ${data.title||'分析报告'}\n\n> ${data._replay?'保存的计算快照，下载时未调用模型或重新查询。':data.mode==='live'?'真实模型工具调用结果。':'确定性演示，未调用大模型。'} 合成数据演示，不代表企业真实经营结果。\n\n运行：${data.run_id||'未记录'}\n\n时间：${data.created_at||'未记录'}\n\n${data.summary||''}\n\n## 关键指标\n\n${(data.kpis||[]).map(k=>`- ${k.label}：${valueText(k.value)} ${k.unit||''}`).join('\n')}\n\n## 分析结论\n\n${(data.findings||[]).map(f=>`- [${{fact:'事实',hypothesis:'假设',action:'行动'}[f.kind]||f.kind}] ${f.text}（证据：${(f.evidence_ids||[]).join('、')||'未指定'}）`).join('\n')}\n\n${(data.tables||[]).map(t=>`## ${t.title}\n\n${rowsToMD(t.rows,t.columns)}\n`).join('\n')}\n## 指标口径\n\n${Object.entries(data.metric_contract||{}).map(([k,v])=>`- ${label(k)}：${valueText(v)}`).join('\n')}\n\n## SQL 与原始证据\n\n${(data.evidence||[]).map(ev=>`### ${ev.label} [${ev.id}]\n\n来源：${ev.source||'未记录'}；口径：${ev.metric_version||'未记录'}\n\n\`\`\`sql\n${ev.sql||''}\n\`\`\`\n\n参数：\`${JSON.stringify(ev.parameters||{})}\`\n\n${rowsToMD(ev.rows)}\n`).join('\n')}\n## 执行记录\n\n${(data.trace||[]).map(t=>`- ${t.tool} / ${t.status}：${t.description}`).join('\n')}\n\n## 使用边界\n\n${(data.limitations||[]).map(l=>`- ${l}`).join('\n')}\n`;
}
function reportHTML(data){return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(data.title||'分析报告')}</title><style>body{margin:40px auto;padding:0 24px;max-width:980px;font:15px/1.85 system-ui,sans-serif;color:#173830}h1{font-size:28px}h2{font-size:20px;margin-top:35px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.8 monospace;background:#eff5ef;padding:20px;border-radius:8px}svg{width:100%;max-height:340px}.chart-legend{display:flex;gap:20px;font-size:12px}.chart-legend span{display:flex;align-items:center;gap:5px}.chart-legend i{display:inline-block;width:9px;height:9px}.data-chart text{font:10px system-ui}.note{font-size:12px;color:#6b8274;border-left:3px solid #87b59b;padding-left:15px}@media print{body{margin:0;max-width:none}section{break-inside:avoid}}</style><h1>${e(data.title||'分析报告')}</h1><p class="note">${data._replay?'保存的计算快照；未重新调用模型。':'由当前运行结果导出。'} 合成数据演示。运行编号 ${e(data.run_id||'未记录')}</p>${(data.charts||[]).map(c=>`<section><h2>${e(c.title)}</h2>${chartHTML(c)}</section>`).join('')}<h2>完整分析、证据与边界</h2><pre>${e(reportMD(data))}</pre></html>`;}
async function downloadReport(format,data,btn){
  const original=btn.innerHTML;btn.disabled=true;
  try{let blob;if(state.online&&!data._replay&&data.run_id){const response=await fetch(url(`/api/v1/runs/${encodeURIComponent(data.run_id)}/report?format=${format}`),{headers:state.accessToken?{Authorization:`Bearer ${state.accessToken}`}:{}});if(!response.ok)throw new Error(`报告下载失败（HTTP ${response.status}），请重新运行后重试。`);blob=await response.blob();}else{blob=new Blob([format==='html'?reportHTML(data):reportMD(data)],{type:format==='html'?'text/html;charset=utf-8':'text/markdown;charset=utf-8'});}const objectURL=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectURL;a.download=`${state.page}-analysis-${(data.run_id||'snapshot').slice(0,8)}.${format}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectURL),1500);toast(format==='html'?'HTML 报告已生成。':'Markdown 报告已生成。');}catch(err){toast(err.message);}finally{btn.disabled=false;btn.innerHTML=original;}
}

async function renderEvaluation(){
  main.innerHTML=`<div class="page-heading"><div><span class="eyebrow">EVALUATION & RELIABILITY</span><h1>把能力放到问题集里验证。</h1><p>分别检查确定性业务流程、模型调用和使用边界。未运行的测试保留“未测”，不以执行成功代替答案正确。</p></div><div class="page-heading-right"><a class="button button-secondary button-small" href="${SOURCE}/tree/main/evals" target="_blank" rel="noopener">评测记录 ${icon('arrow-up')}</a></div></div><div id="evaluation-content"><div class="loading-panel"><span class="spinner"></span><p style="margin-top:15px">正在读取实际评测记录</p></div></div>`;
  let data;try{data=state.online?await fetchJSON(url('/api/v1/evaluations')):await readSnapshot('evaluations');}catch{data={status:'not_run',title:'评测记录暂不可用',metrics:[],cases:[],live_status:'not_run'};}if(state.page!=='evaluation')return;state.evaluation=data;const done=data.status==='completed',metrics=Array.isArray(data.metrics)?data.metrics:[];const cases=Array.isArray(data.cases)?data.cases:[];
  document.querySelector('#evaluation-content').innerHTML=`<div class="eval-hero"><div><span class="eyebrow">MEASURE WHAT ACTUALLY WORKS</span><h2>${e(data.title||'固定样本确定性流程验证')}</h2><p>${done?'以下数据来自已执行的评测记录，验证固定样本下的路由、口径、计算与失败处理。它不等同于开放问题的模型准确率。':'当前没有可核验的完整评测结果。待评测脚本运行并保存结果后，这里会展示真实记录。'}${data.generated_at?`<br>记录时间：${e(new Date(data.generated_at).toLocaleString('zh-CN',{hour12:false}))}`:''}</p></div><div class="eval-status"><strong>${done?'已完成验证':'尚未评测'}</strong><span>${state.online?'后端评测记录':'已保存的评测快照'}</span></div></div>
  <div class="eval-summary-grid"><div class="eval-metric"><span>确定性样本通过</span><strong>${done?`${e(data.passed??'—')} / ${e(data.total??cases.length)}`:'未测'}</strong><small>固定样本 · 以实际断言为准</small></div><div class="eval-metric"><span>真实模型端到端评测</span><strong>${data.live_status==='completed'?'已运行':'未测'}</strong><small>${data.live_status==='completed'?'请查看对应模型版本与详细记录':'不将确定性演示计作 LLM 准确率'}</small></div><div class="eval-metric"><span>人工分析提效对照</span><strong>${data.efficiency_status==='completed'?'已运行':'未测'}</strong><small>需要同标准下的人工核验与修订计时</small></div></div>
  ${(data.first_run_summary||data.audit_summary)?`<div class="notice notice-info" style="margin-bottom:20px">${icon('info')}<p>${data.first_run_summary?`主集首次 ${e(data.first_run_summary.passed)} / ${e(data.first_run_summary.total)} 通过，经问题修复后得到当前回归结果。`:''}${data.audit_summary?` 补充审计首次 ${e(data.audit_summary.first_run_passed??'—')} / ${e(data.audit_summary.total)}，最终 ${e(data.audit_summary.passed)} / ${e(data.audit_summary.total)} 通过。`:''}<br>保留首次失败与修复记录；这些数字不代表大模型准确率。<a class="text-link" style="font-size:inherit;margin-left:5px" href="${SOURCE}/blob/main/docs/evaluation.md" target="_blank" rel="noopener">查看完整评测说明 ↗</a></p></div>`:''}
  ${metrics.length?`<section class="result-section"><div class="result-section-head"><h3>指标与计算方式</h3><span>METRICS</span></div><div class="result-section-body">${tableHTML({columns:['metric','value','unit','description'],rows:metrics.map(m=>({metric:m.label||m.id,value:m.value,unit:m.unit||'',description:m.description||''}))})}</div></section>`:''}
  ${data.splits?`<div class="notice notice-info" style="margin-bottom:20px">${icon('info')}<p>${Object.entries(data.splits).map(([key,v])=>`${key==='development'?'开发集':key==='heldout'?'预留集回归':e(key)}：${e(v.passed??'—')} / ${e(v.total??'—')} 通过`).join('；')}。预留题目在修复过程中已暴露，最终数字仅表示固定样本回归通过，不是未见问题的泛化表现。</p></div>`:''}
  ${cases.length?`<section class="result-section"><div class="result-section-head"><h3>逐题验证记录</h3><span>${cases.length} CASES</span></div><div class="result-section-body">${tableHTML({columns:['id','split','domain','question','category','expected_status','actual_status','passed','duration_ms'],rows:cases.map(c=>({...c,split:c.split==='heldout'?'预留回归':'开发集',domain:c.domain==='growth'?'增长':'复购',passed:c.passed?'通过':'失败',duration_ms:formatNumber(c.duration_ms,1)}))},200)}</div></section>`:''}
  ${sectionHeading('','TEST PRINCIPLES','什么算真正答对？')}
  <div class="method-grid"><article class="method-card"><span class="eyebrow">01 / CORRECTNESS</span><h3>查询成功之后，还要核对答案。</h3><p>按基准结果核对数值、分母、观察窗口和筛选。分别记录 SQL 可执行与业务结果正确。</p></article><article class="method-card"><span class="eyebrow">02 / BOUNDARIES</span><h3>信息不足时，能够停止结论。</h3><p>覆盖口径歧义、无数据、未成熟队列与不支持的请求。清楚区分澄清、拦截和运行错误。</p></article><article class="method-card"><span class="eyebrow">03 / REPRODUCIBILITY</span><h3>结果可以由证据重新算出来。</h3><p>保留请求参数、SQL、数据快照、工具记录和指标版本。重复运行后记录表现与失败类型。</p></article></div>
  ${data.limitations?.length?`<details class="result-limitations" open><summary>本次评测的局限</summary><ul>${data.limitations.map(v=>`<li>${e(v)}</li>`).join('')}</ul></details>`:''}<details class="eval-details"><summary>查看原始评测记录 JSON</summary><pre class="json-view">${e(JSON.stringify(data,null,2))}</pre></details>`;
}

function renderAbout(){
  main.innerHTML=`<div class="page-heading"><div><span class="eyebrow">BEHIND THE ANALYSIS</span><h1>业务方法，落到可运行的工程。</h1><p>从问题定义到交付结果，说明项目如何工作、哪些部分由我实现，以及结论适用的范围。</p></div></div>
  <section class="about-intro"><div><span class="eyebrow">LIU XI / AI DATA ANALYST</span><h2 style="margin-top:12px">理解业务，<br>也把重复工作自动化。</h2><p>这个作品集围绕增长与经营分析，展示业务知识工程、Python 数据接口和 AI 工具调用的结合。新的 Agent 为个人项目，业务案例与实习经历保留在原版作品集中。</p><a class="text-link" href="${OLD}" target="_blank" rel="noopener">查看原版经历与分析案例 ${icon('arrow-up')}</a></div><div class="profile-facts"><div class="profile-fact"><span>求职方向</span><strong>业务型 AI 数据分析师</strong></div><div class="profile-fact"><span>主项目</span><strong>增长诊断与自动周报</strong></div><div class="profile-fact"><span>扩展场景</span><strong>复购诊断与运营方案</strong></div><div class="profile-fact"><span>技术链路</span><strong>Python · SQL · OpenAI · Skill</strong></div><div class="profile-fact"><span>演示数据</span><strong>固定种子合成，可复现</strong></div></div></section>
  ${sectionHeading('01','SYSTEM DESIGN','一条完整的分析链路')}
  <div class="architecture-strip"><div class="architecture-step"><small>CONTEXT</small><strong>业务 Skill</strong><span>指标口径、实体关系、任务边界与 SOP</span></div><span class="architecture-arrow">→</span><div class="architecture-step"><small>PLAN</small><strong>模型任务规划</strong><span>澄清意图，选择允许的工具与参数</span></div><span class="architecture-arrow">→</span><div class="architecture-step"><small>EXECUTE</small><strong>Python + SQL</strong><span>只读查询，确定性分解与统计计算</span></div><span class="architecture-arrow">→</span><div class="architecture-step"><small>DELIVER</small><strong>证据与报告</strong><span>数字可追溯，事实、假设与行动分开</span></div></div>
  <div class="about-grid"><article class="about-card"><div class="about-card-icon">${icon('book')}</div><h3>业务知识与提示词工程</h3><p>将留存窗口、成熟性、分层诊断、实验门槛和复购口径写成版本化业务上下文。运行时加载规则，遇到口径不清或证据不足时返回澄清。</p><a class="text-link" href="${SOURCE}/tree/main/skills" target="_blank" rel="noopener">阅读业务 Skill ${icon('arrow-up')}</a></article><article class="about-card"><div class="about-card-icon">${icon('terminal')}</div><h3>数据接口与工具执行</h3><p>FastAPI 提供任务入口、指标目录、受控查询、运行记录和报告接口。数据库与 Python 负责数值，模型参与任务规划与工具调用。</p><a class="text-link" href="${SOURCE}/tree/main/app" target="_blank" rel="noopener">查看 Python 实现 ${icon('arrow-up')}</a></article><article class="about-card"><div class="about-card-icon">${icon('target')}</div><h3>项目中实现的业务方法</h3><p>增长场景检查成熟留存、结构与组内变化、随机实验和业务门槛；复购场景包含时点 RFM、预算内候选、随机留出与观察窗口校验。</p><a class="text-link" href="${SOURCE}/tree/main/app/domains" target="_blank" rel="noopener">查看分析模块 ${icon('arrow-up')}</a></article><article class="about-card"><div class="about-card-icon">${icon('check')}</div><h3>评测与交付证据</h3><p>用固定问题与断言核验结果，记录成功与失败。模型准确率和人工提效在未实测前保持未测；每次分析保留 SQL、参数和报告。</p><a class="text-link" href="#evaluation">查看实际评测 ${icon('arrow-right')}</a></article></div>
  ${sectionHeading('02','DATA & ATTRIBUTION','数据来源与项目边界')}
  <div class="sources-list"><div class="source-row"><strong>增长演示数据</strong><span>${e(domainMeta('growth')?.data_source||'固定种子合成的用户注册与活动数据')}。用于验证留存、分层和实验计算。</span><a class="text-link" href="${SOURCE}/blob/main/app/domains/growth.py" target="_blank" rel="noopener">生成逻辑 ${icon('arrow-up')}</a></div><div class="source-row"><strong>复购演示数据</strong><span>${e(domainMeta('repurchase')?.data_source||'固定种子合成匿名客户与订单')}。不包含实际触达或真实营销增量。</span><a class="text-link" href="${SOURCE}/blob/main/app/domains/repurchase.py" target="_blank" rel="noopener">生成逻辑 ${icon('arrow-up')}</a></div><div class="source-row"><strong>原版业务作品</strong><span>保留原有作品集、分析材料与经历说明；本项目单独开发，不覆盖旧网址。</span><a class="text-link" href="${OLD}" target="_blank" rel="noopener">原版作品集 ${icon('arrow-up')}</a></div><div class="source-row"><strong>开源基础与参考</strong><span>基于 FastAPI、SQLite 与 OpenAI API；借鉴公开 Skill 的上下文组织方式。具体依赖与许可见仓库。</span><a class="text-link" href="${SOURCE}" target="_blank" rel="noopener">源码与依赖 ${icon('arrow-up')}</a></div></div>
  <div class="notice notice-info" style="margin-top:23px">${icon('info')}<p>确定性演示使用规则路由和参数化查询；真实模式需要后端配置 OpenAI 并成功完成调用。静态回放仅展示已有运行记录。合成数据中的提升、收入与运营候选，不代表真实企业成果。</p></div>
  ${sectionHeading('03','RUN IT YOURSELF','复现与检查')}
  <section class="result-section"><div class="result-section-body"><p class="muted" style="font-size:13px;line-height:1.95">仓库提供环境配置、启动步骤、评测命令和部署说明。运行后可通过工作台发起分析；API 密钥保存在后端环境，浏览器只配置 API 地址。</p><div class="project-actions" style="margin-top:19px"><a class="button button-primary" href="${SOURCE}#readme" target="_blank" rel="noopener">打开项目 README ${icon('arrow-up')}</a><a class="text-link" href="#growth">直接查看分析 ${icon('arrow-right')}</a></div></div></section>`;
}

function openSettings(){document.querySelector('#api-url').value=state.apiBase;document.querySelector('#api-access-token').value=state.accessToken;document.querySelector('#settings-error').textContent='';document.querySelector('#settings-dialog').showModal();}
document.querySelector('#api-settings').addEventListener('click',openSettings);
document.querySelector('#close-settings').addEventListener('click',()=>document.querySelector('#settings-dialog').close());
document.querySelector('#settings-dialog').addEventListener('click',event=>{if(event.target===event.currentTarget){const r=event.currentTarget.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.currentTarget.close();}});
document.querySelector('#settings-form').addEventListener('submit',async event=>{event.preventDefault();let value=document.querySelector('#api-url').value.trim().replace(/\/+$/,'');try{if(value){const u=new URL(value);if(!['https:','http:'].includes(u.protocol))throw new Error('请使用 http 或 https 地址。');if(u.username||u.password||u.search||u.hash)throw new Error('地址中不能包含密码、查询参数或片段。');if(u.pathname.endsWith('/api/v1'))value=value.slice(0,-7);}}catch(err){document.querySelector('#settings-error').textContent=err.message==='Invalid URL'?'请填写完整的后端根地址，例如 https://your-api.example.com。':err.message;return;}const token=document.querySelector('#api-access-token').value.trim();if(/^sk-/.test(token)){document.querySelector('#settings-error').textContent='此处只接收部署访问令牌。请勿填写 OpenAI API Key；模型密钥应在后端环境配置。';return;}if(token&&value&&new URL(value).protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(new URL(value).hostname)){document.querySelector('#settings-error').textContent='远程访问令牌需要 HTTPS 连接。';return;}state.apiBase=value;state.accessToken=token;document.querySelector('#api-access-token').value='';saveStorage('lx-analyst-api',value);state.controller?.abort();state.snapshots={};document.querySelector('#settings-dialog').close();await connect();toast(state.online?'分析 API 已连接，可提交新问题。':'暂时无法连接 API，当前展示静态回放。');});
document.querySelector('#reset-settings').addEventListener('click',async()=>{state.apiBase='';state.accessToken='';document.querySelector('#api-access-token').value='';saveStorage('lx-analyst-api','');state.controller?.abort();document.querySelector('#settings-dialog').close();await connect();toast(state.online?'已恢复默认 API 连接。':'已恢复默认连接，当前为静态回放。');});
document.querySelector('#mobile-toggle').addEventListener('click',()=>{const open=document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#mobile-toggle').setAttribute('aria-expanded',String(open));updateSidebarAccessibility();});
document.addEventListener('click',event=>{if(innerWidth<=680&&!event.target.closest('#sidebar')&&!event.target.closest('#mobile-toggle')){document.querySelector('#sidebar').classList.remove('open');document.querySelector('#mobile-toggle').setAttribute('aria-expanded','false');updateSidebarAccessibility();}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.querySelector('#sidebar').classList.remove('open');document.querySelector('#mobile-toggle').setAttribute('aria-expanded','false');updateSidebarAccessibility();}});
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'instant'});});
function updateSidebarAccessibility(){const sidebar=document.querySelector('#sidebar');const hidden=innerWidth<=680&&!sidebar.classList.contains('open');sidebar.inert=hidden;sidebar.setAttribute('aria-hidden',String(hidden));}
window.addEventListener('resize',updateSidebarAccessibility);
hydrateIcons();render();connect();
