import {escape as e, icon, formatNumber, label, valueText, displayValue, tableHTML, chartHTML} from './ui.js';
export const arr = v => Array.isArray(v) ? v : [];
export const text = v => v == null ? '—' : typeof v === 'object' ? JSON.stringify(v) : String(v);
export function analysisMode({online=false,catalog={},mode='demo'}={}){
  const canCallModel=online&&catalog.model?.configured===true;
  const requestMode=mode==='live'&&canCallModel?'live':'demo';
  if(!online)return {kind:'static',requestMode,canCallModel:false,label:'静态案例',button:'重新载入案例',hint:'保存结果 · 只读查看',help:'读取已保存结果，不执行新问题，不调用模型。',connection:'静态案例'};
  if(requestMode==='live')return {kind:'live',requestMode,canCallModel,label:'模型分析',button:'调用模型分析',hint:'服务端模型 · 工具调用',help:'向模型提交问题；结果须有模型调用记录才能标记为已核验。',connection:'API · 模型已配置'};
  return {kind:'demo',requestMode,canCallModel,label:'Python 规则分析',button:'运行规则分析',hint:'SQL / Python · 只读查询',help:`${canCallModel?'':'模型未配置。'}Python 规则仅匹配预设任务，不调用模型；日期、渠道、设备以表单为准。`,connection:canCallModel?'API · 模型已配置':'API · 模型未配置'};
}
export function resultExecution(data={}){
  const run=data.model_run||{};
  const verifiedLive=data.mode==='live'&&run.provider==='OpenAI'&&run.live_verified===true;
  if(data._replay||data.static_snapshot===true)return {kind:'static',verifiedLive,label:'静态案例',description:verifiedLive?'历史记录含已核验的模型调用；本次仅查看保存结果。':'本次读取已保存结果，未执行新查询或模型调用。'};
  if(data.mode==='demo')return {kind:'demo',verifiedLive:false,label:'Python 规则分析',description:'本次使用 Python 规则分析，未调用模型。'};
  if(verifiedLive)return {kind:'verified_live',verifiedLive:true,label:'已核验模型调用',description:`已记录 ${run.provider} / ${run.model||'未记录模型名'} 的模型调用；业务数值由 SQL 与 Python 计算。`};
  if(data.mode==='live'&&run.provider==='test-double')return {kind:'test_double',verifiedLive:false,label:'测试替身',description:'本次使用测试替身，未作为真实模型调用记录。'};
  if(data.mode==='live')return {kind:'unverified_live',verifiedLive:false,label:'模型调用未核验',description:'请求使用模型模式，但缺少真实调用核验记录。'};
  return {kind:'unknown',verifiedLive:false,label:'运行方式未记录',description:'当前结果缺少运行方式记录。'};
}
export function modelRunMetadata(data={}){
  if(data.mode!=='live'&&!data.model_run)return null;
  const run=data.model_run||{},raw=run.usage||{};
  const usage=Object.fromEntries(['input_tokens','output_tokens'].map(key=>[key,typeof raw[key]==='number'&&Number.isFinite(raw[key])&&raw[key]>=0?raw[key]:null]));
  let status=['complete','partial','unknown'].includes(run.usage_status)?run.usage_status:'unknown';
  if(status==='complete'&&Object.values(usage).some(v=>v===null))status=Object.values(usage).some(v=>v!==null)?'partial':'unknown';
  const metadata=Object.fromEntries(['provider','model','rounds'].filter(key=>run[key]!==undefined).map(key=>[key,run[key]]));
  Object.assign(metadata,{live_verified:resultExecution(data).verifiedLive,usage_status:status,usage:status==='complete'?usage:{input_tokens:null,output_tokens:null}});
  if(status==='partial')metadata.known_usage=usage;
  metadata.usage_note={complete:'已记录全部响应的用量。',partial:'仅记录部分响应用量；known_usage 为已知部分，完整总量未知。',unknown:'未获得完整用量记录；空值不代表零。'}[status];
  return metadata;
}
export function modelRunHTML(data={}){
  if(data.mode!=='live'&&!data.model_run)return '';
  const run=data.model_run||{},mode=resultExecution(data);
  return `<details class="result-limitations"><summary>模型调用记录</summary>${kvHTML({requested_mode:data.mode==='live'?'模型分析':data.mode==='demo'?'Python 规则分析':'未记录',provider:run.provider||'未记录',model:run.model||'未记录',live_verified:mode.verifiedLive?'已核验':'未核验',rounds:run.rounds??null,usage_status:displayValue('usage_status',run.usage_status)||'未记录'})}</details>`;
}
export const statusLabel = v => ({completed:'计算完成',passed:'通过',pass:'通过',success:'通过',healthy:'正常',ok:'通过',warning:'需关注',warn:'需关注',failed:'未通过',fail:'未通过',blocked:'已暂停',data_quality_blocked:'数据需修复',needs_clarification:'需澄清',insufficient_data:'数据不足',not_run:'未运行',not_recorded:'未记录',needs_repair:'数据需修复',wait_for_maturity:'等待成熟',insufficient_evidence:'证据不足',stop_or_adjust:'停止或调整',ready_for_review:'符合预设条件',supported:'证据支持',rejected:'证据不支持',unresolved:'尚待验证',invalid_data:'数据无效',waiting_for_maturity:'等待成熟',review_for_gradual_rollout:'人工灰度评审',repair_data:'修复数据',investigate_then_experiment:'诊断后验证',descriptive_support:'描述性支持',needs_validation:'需进一步验证',not_supported_in_scope:'当前证据不支持',pending:'尚未执行',replay_of_executed_batches:'已执行批次回放',configured:'已配置',not_configured:'未配置',active:'触发中',resolved:'已恢复',recovered:'已恢复',open:'触发中',demo:'Python 规则分析',live:'模型模式'}[v] || text(v));
export function badge(v){const danger=/fail|block|repair|stop|gap|invalid/.test(String(v));const good=/complete|pass|success|healthy|resolved|recover|ready/.test(String(v));return `<span class="tag ${danger?'tag-red':good?'tag-green':'tag-amber'}">${e(statusLabel(v))}</span>`;}
export function kvHTML(obj,depth=0){if(obj==null)return '<span class="muted">未记录</span>';if(typeof obj!=='object')return `<span>${e(text(obj))}</span>`;if(Array.isArray(obj)){if(!obj.length)return '<span class="muted">无记录</span>';if(obj.every(v=>typeof v!=='object'))return `<ul class="simple-list">${obj.map(v=>`<li>${e(v)}</li>`).join('')}</ul>`;return obj.map(v=>`<div class="nested-block">${kvHTML(v,depth+1)}</div>`).join('');}return `<dl class="detail-grid depth-${Math.min(depth,2)}">${Object.entries(obj).map(([k,v])=>`<dt>${e(label(k))}</dt><dd>${typeof v==='object'?kvHTML(v,depth+1):e(typeof v==='boolean'?(v?'是':'否'):text(v))}</dd>`).join('')}</dl>`;}
export function heading(kicker,title,description,action=''){return `<div class="page-heading"><div><span class="eyebrow">${e(kicker)}</span><h1>${e(title)}</h1><p>${e(description)}</p></div>${action?`<div class="page-heading-right">${action}</div>`:''}</div>`;}
export function section(kicker,title,description='',action=''){return `<div class="section-heading"><div><span class="eyebrow">${e(kicker)}</span><h2>${e(title)}</h2>${description?`<p>${e(description)}</p>`:''}</div>${action}</div>`;}
export function kpiHTML(k){const ratio=['ratio','proportion'].includes(k.unit),value=typeof k.value==='number'&&ratio?k.value*100:k.value;const unit={ratio:'%',proportion:'%',count:'人',customers:'人',CNY:'元'}[k.unit]||k.unit||'';return `<div class="kpi-card"><div class="kpi-label">${e(k.label||k.id)}</div><div class="kpi-value">${e((/(_p$|p_value|^p$)/.test(k.id||'')&&typeof value==='number')?(value!==0&&Math.abs(value)<0.001?value.toExponential(2):formatNumber(value,4)):formatNumber(value))}<span>${e(unit)}</span></div>${k.previous!==undefined?`<div class="kpi-change">对比期 <b>${e(formatNumber(ratio&&k.previous!==null?k.previous*100:k.previous))}${e(unit)}</b>${k.delta!==undefined?` · 变化 ${Number(k.delta)>0?'+':''}${e(formatNumber(k.delta))}${e(k.delta_unit||(unit==='%'?'个百分点':unit))}`:''}</div>`:`<div class="kpi-change">${e(k.note||'来源：本次计算')}</div>`}</div>`;}
export function evidenceHTML(evidence){return arr(evidence).length?evidence.map((item,i)=>`<details class="evidence-card" id="evidence-${e(item.id||i)}"><summary><span>${e(item.label||item.id||'查询证据')} <code>${e(item.id||'')}</code></span>${icon('chevron')}</summary><div class="evidence-info">来源：${e(item.source||'确定性计算')} · 口径：${e(item.metric_version||'随本次指标合同')}<br>参数：<span class="raw-value">${e(JSON.stringify(item.parameters??{}))}</span></div><div class="code-toolbar"><span>EXECUTED SQL / TOOL</span><button class="text-link copy-sql" type="button">复制</button></div><pre><code>${e(item.sql||'该证据来自 Python 统计计算，结果随运行记录保存。')}</code></pre>${tableHTML({rows:item.rows||[]},40)}</details>`).join(''):'<div class="empty-note">此结果没有执行查询，未产生 SQL 证据。</div>';}
export function traceHTML(trace){return arr(trace).length?`<div class="trace-list">${trace.map((t,i)=>`<div class="trace-item"><span class="trace-dot">${String(i+1).padStart(2,'0')}</span><div><div class="trace-title"><code>${e(t.tool||t.step||'tool')}</code>${badge(t.status||'completed')}</div><p class="trace-description">${e(t.description||t.purpose||'')}</p>${t.input?`<details class="inline-detail"><summary>输入参数</summary><pre>${e(JSON.stringify(t.input,null,2))}</pre></details>`:''}</div><span class="trace-time">${t.duration_ms!==undefined?`${e(formatNumber(t.duration_ms,1))} ms`:''}</span></div>`).join('')}</div>`:'<div class="empty-note">此结果没有执行记录。</div>';}
export function decisionHTML(d){if(!d)return '';if(typeof d==='string')return `<div class="decision-card"><span class="eyebrow">DECISION MEMO</span><h3>${e(d)}</h3></div>`;const status=d.status||d.code,actions=arr(d.actions).length?d.actions:d.action?[d.action]:[];return `<section class="decision-card ${/repair|invalid|stop|block/.test(status)?'decision-caution':''}"><div class="decision-top"><span class="eyebrow">DECISION MEMO / 决策备忘录</span>${status?badge(status):''}</div><h3>${e(d.label||d.title||d.recommendation||'本次决策')}</h3>${d.reason||d.rationale?`<p>${e(text(d.reason||d.rationale))}</p>`:''}${actions.length?`<div class="decision-actions">${actions.map((a,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${typeof a==='object'?kvHTML(a):e(a)}</span></div>`).join('')}</div>`:''}${d.review_trigger?`<div class="review-trigger">${icon('clock')}<span>复查条件：${e(text(d.review_trigger))}</span></div>`:''}</section>`;}
export function checksHTML(checks){if(!Array.isArray(checks))return kvHTML(checks);return `<div class="check-list">${checks.map(c=>`<details class="check-item" ${(c.passed===false||/blocked|failed/.test(c.status||''))?'open':''}><summary><span class="check-mark ${(c.passed===false||/blocked|failed/.test(c.status||''))?'failed':''}">${icon((c.passed===false||/blocked|failed/.test(c.status||''))?'close':'tick')}</span><strong>${e(c.label||c.name||c.id)}</strong><span class="check-observed">${e(typeof c.observed==='number'?formatNumber(c.observed,4):text(c.observed))}</span>${badge(c.passed===false?'failed':c.status||'passed')}</summary><div class="check-explanation"><p>${e(c.rule||c.detail||'')}</p>${arr(c.evidence_ids).length?`<div class="evidence-links">${c.evidence_ids.map(id=>`<button type="button" class="evidence-reference" data-evidence="${e(id)}">↳ ${e(id)}</button>`).join('')}</div>`:''}</div></details>`).join('')}</div>`;}
export function hypothesesHTML(hypotheses){if(!arr(hypotheses).length)return '';return `<section class="result-section"><div class="result-section-head"><h3>待验证项与证据</h3><span>HYPOTHESES</span></div><div class="hypothesis-grid">${hypotheses.map((h,i)=>`<article class="hypothesis-card"><div><span class="eyebrow">H${i+1} / ${e(h.id||'')}</span>${h.status?badge(h.status):''}</div><h4>${e(h.title||h.hypothesis||'待验证项')}</h4>${h.supporting_evidence_ids?.length?`<p class="hypothesis-label">相关证据</p><div class="evidence-links">${h.supporting_evidence_ids.map(id=>`<button type="button" class="evidence-reference" data-evidence="${e(id)}">↳ ${e(id)}</button>`).join('')}</div>`:''}${h.observation?`<p class="hypothesis-observation">${e(h.observation)}</p>`:''}${h.counter_evidence?`<p class="hypothesis-label">证据限制</p><p>${e(text(h.counter_evidence))}</p>`:''}${h.next_test?`<p class="hypothesis-label">验证方法</p><p>${e(text(h.next_test))}</p>`:''}</article>`).join('')}</div></section>`;}
export function qualityHTML(q){if(!q)return '';return `<details class="quality-card" ${q.status&&/block|fail|warn|incomplete/.test(q.status)?'open':''}><summary><span>${icon('database')}数据质量与新鲜度</span>${badge(q.status||'recorded')}</summary><div class="quality-meta"><span>分析截至 ${e(q.as_of||'随运行记录')}</span><span>数据水位 ${e(text(q.watermark||'未记录'))}</span></div>${q.checks?checksHTML(q.checks):''}${q.affected_metrics?.length?`<p class="field-help">受影响指标：${e(q.affected_metrics.map(label).join('、'))}</p>`:''}</details>`;}
export function funnelHTML(funnel){if(!funnel||!arr(funnel.steps).length)return '';const steps=funnel.steps;const getValue=s=>s.users??s.count??s.user_count??s.current_users??s.value;const max=Math.max(...steps.map(s=>Number(getValue(s))||0),1);return `<section class="result-section"><div class="result-section-head"><h3>注册后的有序转化路径</h3><span>ORDERED FUNNEL</span></div><div class="result-section-body"><p class="field-help">窗口：${e(text(funnel.window))} · ${e(text(funnel.maturity))}</p><div class="funnel-list">${steps.map((s,i)=>`<div class="funnel-step"><span class="funnel-step-no">${String(i+1).padStart(2,'0')}</span><div><strong>${e(s.label||s.name||label(s.step||s.event||s.id||'step'))}</strong><div class="funnel-track"><i style="width:${Math.max(2,(Number(getValue(s))||0)/max*100)}%"></i></div></div><span>${e(formatNumber(getValue(s)))}<small>人</small></span></div>`).join('')}</div>${funnel.largest_drop?`<div class="funnel-foot">最大损失环节：${e(typeof funnel.largest_drop==='object'?`${funnel.largest_drop.step||funnel.largest_drop.label||'路径步骤'} · 本期流失 ${formatNumber(funnel.largest_drop.current_lost_users)} 人 · 步骤转化变化 ${formatNumber(funnel.largest_drop.step_delta_pp)} 个百分点`:text(funnel.largest_drop))}</div>`:''}</div></section>`;}
export function findingsHTML(findings){return arr(findings).length?`<section class="result-section"><div class="result-section-head"><h3>事实、待验证项与行动</h3><span>EVIDENCE → ACTION</span></div><div class="finding-list">${findings.map(f=>`<div class="finding-item"><span class="finding-kind ${e(f.kind)}">${{fact:'事实',hypothesis:'待验证',action:'行动'}[f.kind]||'说明'}</span><div>${e(f.text||text(f))}${f.evidence_ids?.length?`<div class="evidence-links">${f.evidence_ids.map(id=>`<button type="button" class="evidence-reference" data-evidence="${e(id)}">↳ ${e(id)}</button>`).join('')}</div>`:''}</div></div>`).join('')}</div></section>`:'';}
export function reportMD(data){const rowsToMD=(rows,columns)=>{if(!rows?.length)return '_无数据_';const cols=columns?.length?columns.map(c=>typeof c==='object'?c.key:c):Object.keys(rows[0]);const cell=v=>valueText(v).replaceAll('|','\\|').replaceAll('\n',' ');return `| ${cols.map(label).join(' | ')} |\n| ${cols.map(()=> '---').join(' | ')} |\n${rows.map(r=>`| ${cols.map(c=>cell(r[c])).join(' | ')} |`).join('\n')}`;};return `# ${data.title||'分析报告'}\n\n> ${resultExecution(data).label}。${resultExecution(data).description} 数据来源见指标合同。\n\n运行：${data.run_id||'未记录'}\n\n时间：${data.created_at||'未记录'}\n\n${data.summary||''}\n\n## 决策\n\n${JSON.stringify(data.decision||{},null,2)}\n\n## 关键指标\n\n${arr(data.kpis).map(k=>`- ${k.label}：${valueText(k.value)} ${k.unit||''}`).join('\n')}\n\n## 分析结论\n\n${arr(data.findings).map(f=>`- [${f.kind}] ${f.text}（证据：${arr(f.evidence_ids).join('、')||'未指定'}）`).join('\n')}\n\n${arr(data.tables).map(t=>`## ${t.title}\n\n${rowsToMD(t.rows,t.columns)}\n`).join('\n')}\n## 指标口径\n\n\`\`\`json\n${JSON.stringify(data.metric_contract||{},null,2)}\n\`\`\`\n\n## SQL 与原始证据\n\n${arr(data.evidence).map(ev=>`### ${ev.label} [${ev.id}]\n\n来源：${ev.source||'未记录'}；口径：${ev.metric_version||'未记录'}\n\n\`\`\`sql\n${ev.sql||''}\n\`\`\`\n\n参数：\`${JSON.stringify(ev.parameters||{})}\`\n\n${rowsToMD(ev.rows)}\n`).join('\n')}\n## 检查与执行\n\n\`\`\`json\n${JSON.stringify({data_quality:data.data_quality,checks:data.checks,plan:data.plan,hypotheses:data.hypotheses,trace:data.trace,...(modelRunMetadata(data)?{model_run:modelRunMetadata(data)}:{})},null,2)}\n\`\`\`\n\n## 使用边界\n\n${arr(data.limitations).map(l=>`- ${l}`).join('\n')}\n`;}
export function reportHTML(data){return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(data.title||'分析报告')}</title><style>body{margin:40px auto;padding:0 24px;max-width:1000px;font:15px/1.85 system-ui,sans-serif;color:#183745}h1{font-size:28px}h2{font-size:20px;margin-top:32px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.8 monospace;background:#f1f5f4;padding:20px;border-radius:8px}svg{width:100%;max-height:340px}.chart-legend{display:flex;gap:20px;font-size:12px}.chart-legend span{display:flex;align-items:center;gap:5px}.chart-legend i{display:inline-block;width:9px;height:9px}.note{font-size:12px;color:#607584;border-left:3px solid #36a78e;padding-left:15px}@media print{body{margin:0;max-width:none}section{break-inside:avoid}}</style><h1>${e(data.title||'分析报告')}</h1><p class="note">${e(resultExecution(data).label)}。${e(resultExecution(data).description)} 运行编号 ${e(data.run_id||'未记录')}</p><p>${e(data.summary||'')}</p>${arr(data.charts).map(c=>`<section><h2>${e(c.title)}</h2>${chartHTML(c)}</section>`).join('')}<h2>完整分析、证据与边界</h2><pre>${e(reportMD(data))}</pre></html>`;}

export function requestWindow(result={}){const req=result.request||{},contract=result.metric_contract||{},current=contract.experiment_period||contract.current_period||contract.window||{},previous=contract.previous_period||contract.comparison_period||{};return {start:req.start||(Array.isArray(current)?current[0]:current.start)||'',end:req.end||(Array.isArray(current)?current[1]:current.end)||'',compare_start:req.compare_start||(Array.isArray(previous)?previous[0]:previous.start)||'',compare_end:req.compare_end||(Array.isArray(previous)?previous[1]:previous.end)||''};}

export function studyProtocolHTML({completed=false}={}){return `<section class="case-resource-card study-protocol-card"><div><span class="eyebrow">USER STUDY / EXECUTION PROTOCOL</span><h3>真实试用协议与记录模板</h3><p>${completed?'研究执行状态以实际参与者与任务记录为准。':'真实用户研究尚未开展。'}可下载任务、核验、计时及复测模板；协议本身不是试用结果或提效证据。</p></div><div><a class="button button-secondary" href="./resources/user-study.html" target="_blank" rel="noopener">打开执行协议 ↗</a><a class="text-link" href="./resources/user-study.html" download>下载协议与模板 ↓</a></div></section>`;}
